%YAML:1.0

# MAIN

LOG_Threshold: 0
Init_Frame_Index: 0
USE_GT_DATA: 1


# Input/Output directories and Sets
Output.Directory.LOG_DIR: "./Log/"


USE_VIDEO: 1
Calib_FX: 827.03599
Calib_FY: 821.06273
Calib_CX: 329.14773
Calib_CY: 186.90243
Input.Directory.Obj: "/Users/flamming/WorkSpace/HistogramTracker/Files/Models/Renderer/long.obj"
Input.Directory.Video: "./data/cat/cat_video.avi"
Input.Directory.GroudTruth: "./data/cat/cat_gtpose.txt"
Input.Directory.DISTORTIONS: "./data/cat/distortions.txt"
VIDEO_WIDTH: 640
VIDEO_HEIGHT: 480

#CV
CV_DRAW_FRAME: 1

#track
TK_VER_NUMBER: 100
H_SOFT_COEF: 1.0

#IMG
IMG_PYR_NUMBER: 5
IMG_DT_WEIGHT: 8

